"""empty message

Revision ID: 0266ebbe32b2
Revises: 
Create Date: 2021-01-11 15:10:12.163707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0266ebbe32b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=2083), nullable=True),
    sa.Column('duracao', sa.Time(), nullable=True),
    sa.Column('genero_musical', sa.String(length=30), nullable=False),
    sa.Column('idioma', sa.String(length=30), nullable=False),
    sa.Column('formato', sa.String(length=30), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('pais', sa.String(length=30), nullable=False),
    sa.Column('genero_musical', sa.String(length=30), nullable=False),
    sa.Column('img', sa.String(length=2083), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artista')
    op.drop_table('album')
    # ### end Alembic commands ###
