"""n para n

Revision ID: 3da7352d87c2
Revises: 0266ebbe32b2
Create Date: 2021-01-11 17:10:41.120280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da7352d87c2'
down_revision = '0266ebbe32b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistaAlbum',
    sa.Column('id_artista', sa.Integer(), nullable=True),
    sa.Column('id_album', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_album'], ['album.id'], ),
    sa.ForeignKeyConstraint(['id_artista'], ['artista.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artistaAlbum')
    # ### end Alembic commands ###
