"""empty message

Revision ID: 523413a15dc8
Revises: 6739f10e3141
Create Date: 2021-01-09 00:20:17.510473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523413a15dc8'
down_revision = '6739f10e3141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=2083), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('genero_musical', sa.String(length=30), nullable=False),
    sa.Column('idioma', sa.String(length=30), nullable=False),
    sa.Column('formato', sa.String(length=30), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album')
    # ### end Alembic commands ###
