"""empty message

Revision ID: 6739f10e3141
Revises: 
Create Date: 2021-01-08 19:29:23.925976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6739f10e3141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('pais', sa.String(length=30), nullable=False),
    sa.Column('genero_musical', sa.String(length=30), nullable=False),
    sa.Column('img', sa.String(length=2083), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artista')
    # ### end Alembic commands ###
