"""empty message

Revision ID: c2fb1536c8ed
Revises: 523413a15dc8
Create Date: 2021-01-11 10:56:20.674972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb1536c8ed'
down_revision = '523413a15dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album', 'img',
               existing_type=sa.VARCHAR(length=2083),
               nullable=True)
    op.alter_column('artista', 'img',
               existing_type=sa.VARCHAR(length=2083),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artista', 'img',
               existing_type=sa.VARCHAR(length=2083),
               nullable=False)
    op.alter_column('album', 'img',
               existing_type=sa.VARCHAR(length=2083),
               nullable=False)
    # ### end Alembic commands ###
