"""adicionando a tupla media

Revision ID: ebb149fa39c8
Revises: 3da7352d87c2
Create Date: 2021-01-14 09:37:42.223679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb149fa39c8'
down_revision = '3da7352d87c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artista', sa.Column('media', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artista', 'media')
    # ### end Alembic commands ###
